assembleiaproject/base/urls.py
from django.urls import path
from assembleiaproject.base.views import home, about_us

app_name = 'base'

urlpatterns = [
    path('', home, name='home'),
    path('sobre-nos', about_us, name='about_us'),
]

assembleiaproject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<slug:post>/', views.post_detail, name='post_detail')
]

assembleiaproject/contact/urls.py
from django.urls import path
from .views import contact_us, get_message


app_name = 'contact'

urlpatterns = [
    path('', contact_us, name='contact_us'),
    path('message/', get_message, name='get_message')
]

assembleiaproject/gallery/urls.py
from django.urls import path
from assembleiaproject.gallery.views import gallery, photo_detail

app_name = 'gallery'

urlpatterns = [
    path('', gallery, name='gallery'),
    path('imagem/<slug:slug>/', photo_detail, name='photo_detail')

]

assembleiaproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assembleiaproject.base.urls')),
    path('blog/', include('assembleiaproject.blog.urls')),
    path('galeria/', include('assembleiaproject.gallery.urls')),
    path('account/', include('assembleiaproject.account.urls')),
    path('contato/', include('assembleiaproject.contact.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'assembleiaproject.base.views.handler500'
handler404 = 'assembleiaproject.base.views.handler404'

assembleiaproject/base/models.py
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from django.db.models.signals import post_save
from django.dispatch import receiver


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    email_verified = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    date_of_birth = models.DateField(_('date of birth'), blank=True, null=True)
    photo = models.ImageField(_('photo'), upload_to='users/%Y/%m/', blank=True)

    class Meta:
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

    def __str__(self):
        return f'Perfil para o usuário {self.user.first_name}'


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

assembleiaproject/base/views.py
from django.shortcuts import render

from assembleiaproject.blog.models import Post
from assembleiaproject.gallery.models import Image


def home(request):
    posts = Post.published.all()[:6]
    photos = Image.photopublished.all()[:4]

    context = {'posts': posts,
               'photos': photos,
               'section': 'home',
               }

    return render(request, 'home.html', context)


def about_us(request):
    context = {'section': 'about_us'}
    return render(request, 'about-us.html', context)


def handler500(request):
    response = render(request, 'errors/error-500.html')
    response.status_code = 500
    return response


def handler404(request, exception):
    response = render(request, 'errors/error-404.html')
    response.status_code = 404
    return response

assembleiaproject/base/templates/about-us.html
{% extends 'base.html' %}
{% block title %} Sobre nós {% endblock title %}

{% block content %}
    <section class="container">
    <h4 class="text-center mt-5 mb-5">Área em desenvolvimento</h4>

    </section>
{% endblock content %}

assembleiaproject/base/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Assembleia {% endblock %}</title>
    <meta name="description" content="Igreja assembleia">
    <meta name="author" content="Helton Teixeira">
    <meta name="keywords" content="church, God,  igreja, Deus">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'base/img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'base/img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'base/img/site.webmanifest' %}">

    <link href="{% static 'base/css/style.css' %}" rel="stylesheet">
    {% block extracss %}
    {% endblock extracss %}
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/scripts.js' %}"></script>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>

<header class=" nav-style text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 ml-lg-0 text-white text-decoration-none">
                <img class="navbar-brand logo"  src="{% static 'base/img/logo-nav.png' %}">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'base:home' %}" {% if section == 'home' %} class="nav-link text-secondary" {% else %} class="nav-link  text-white"{% endif %}>Home</a></li>
                <li><a href="{% url 'gallery:gallery' %}" {% if section == 'gallery' %} class="nav-link  text-secondary" {% else %} class="nav-link text-white"{% endif %}>Galeria</a></li>
                <li><a href="{% url 'blog:post_list' %}" {% if section == 'blog' %} class="nav-link  text-secondary" {% else %} class="nav-link  text-white"{% endif %}>Blog</a></li>
                <li><a href="{% url 'base:about_us' %}" {% if section == 'about_us' %} class="nav-link  text-secondary" {% else %} class="nav-link  text-white"{% endif %}>Sobre nós</a></li>
                <li><a href="{% url 'contact:contact_us' %}" {% if section == 'contact_us' %} class="nav-link  text-secondary" {% else %} class="nav-link  text-white"{% endif %}>Contato</a></li>
                {% if user.is_authenticated and user.is_staff %}
                <li><a href="{% url 'admin:index' %}" class="nav-link  text-white">Admin</a></li>
                {% endif %}
            </ul>

<!--            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">-->
<!--                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">-->
<!--            </form>-->

            <div class="text-end">
                {% if user.is_authenticated %}
                     <a href="{% url 'logout' %}">
                    <button type="button" class="btn btn-outline-light me-2">Sair</button>
                     </a>
                {% else %}
                    <a href="{% url 'login' %}">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

    <main role="main">
  {% block content %}
  {% endblock %}
    </main>

<!-- FOOTER (rodapé)-->
<div class="d-flex flex-column h-100">

{#    <!-- FOR DEMO PURPOSE -->#}
{#    <section class="hero text-white py-5 flex-grow-1">#}
{#        <div class="container py-4">#}
{#            <div class="row">#}
{#                <div class="col-lg-6">#}
{#                    <h1 class="display-4">Bootstrap footer bottom</h1>#}
{#<!--                    <p class="fst-italic text-muted">Using Bootstrap 5 flexbox utilities, create a footer that always sticks to the bottom of your viewport. Snippet by <a class="text-primary" href="https://bootstrapious.com/" target="_blank">Bootstrapious</a></p>-->#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}

    <footer class="w-100 py-4 flex-shrink-0">
        <div class="container py-4">
            <div class="row gy-4 gx-5">
                <div class="col-lg-4 col-md-6">
                    <h5 class="h1 text-white">Contato</h5>
                    <p class="small text-muted">Telefone: <a href="tel:+5511982436412" class="text-light">(11) 98243-6412</a> </p>
<!--                     <p class="small text-muted">Telefone: <a href="tel:+551132282064" class="text-light">(11) 3311-7864</a>  </p>-->
                    <p class="small text-muted">Sede: Rua Ateneu nº 165, Montes claros - MG </p>
                    <p class="small text-muted">Setor 2: Av Dois, nº 401, Recanto das águas - MG</p>
                    <p class="small text-muted">Setor 3: Rua Lago da vitória nº 26b, <br>Jardim Aurélio, Sâo Paulo - SP</p>
{#                    <p class="small text-muted mb-0">&copy; Copyrights. All rights reserved. <a class="text-primary" href="#">Bootstrapious.com</a></p>#}
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Links</h5>
                    <ul class="list-unstyled text-muted">
                        <li><a href="{% url 'base:home' %}">Home</a></li>
                        <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
                        <li><a href="{% url 'base:about_us' %}">FAQ</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Redes Sociais</h5>
                    <ul class="list-unstyled text-muted">
                        <li><img src="{% static 'base/img/intagram.png' %}" height="20" width="20" alt="icone instagram" /> iadmissionaria01</li>
<!--                        <li><a href="#">FAQ</a></li>-->
                    </ul>
                </div>
{#                <div class="col-lg-4 col-md-6">#}
{#                    <h5 class="text-white mb-3">Newsletter</h5>#}
{#                    <p class="small text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>#}
{#                    <form action="#">#}
{#                        <div class="input-group mb-3">#}
{#                            <input class="form-control" type="text" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">#}
{#                            <button class="btn btn-primary" id="button-addon2" type="button"><i class="fas fa-paper-plane"></i></button>#}
{#                        </div>#}
{#                    </form>#}
{#                </div>#}
            </div>
        </div>
    </footer>
</div>

</div>
</div>
<div class="rights pl-5 pb-2">
    <div class="row">
        <div class="col-md-auto pt-4">
            <!--                                        <img src="{% static 'base/img/logo-assembleia.png' %}" height="65" width="110" alt="Logo Assembleia"  />-->
        </div>
        <div class="col pt-4">
            <h5 class="text-center">Louvado seja o senhor. <br>
                Conheça nosso trabalho: https://www.facebook.com/xxxxx</h5>
        </div>
    </div>
</div>

    {% block extrajs %}
    
    {% endblock extrajs %}

</body>
</html>

assembleiaproject/base/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <img class="logo-capa img-fluid" src="{% static 'base/img/logo-nav.png' %}">
                <!--        <h1 class="fw-light">Album example</h1>-->
                <!--        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>-->
                <!--        <p>-->
                <!--          <a href="#" class="btn btn-primary my-2">Main call to action</a>-->
                <!--          <a href="#" class="btn btn-secondary my-2">Secondary action</a>-->
                <!--        </p>-->
            </div>
        </div>
    </section>
     <section class="text-center pb-4 pt-3 section-blue text-white">
        <div class="container">

            <h1 class="fw-light text-center text-lg-start mt-4 mb-0">Galeria</h1>

            <hr class="mt-2 mb-5">

            <div class="row text-center text-lg-start">

                {% for photo in photos %}
                <div class="col-lg-3 col-md-4 col-6">
                    <a href="{{ photo.img.url }}" class="d-block mb-4 h-100">
                        <img class="img-fluid img-thumbnail" src="{{ photo.img.url }}"
                             alt="{{ photo.description }}">
                    </a>
                </div>
                {% endfor %}
            </div>

        </div>
    </section>

    <div class="section sec-cta overlay" style="background-color: gray">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-lg-5" data-aos="fade-up" data-aos-delay="0">
                    <h2 class="heading text-white">Quer falar conosco?</h2>
                    <p class="text-white">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts. </p>
                </div>
                <div class="col-lg-5 text-end" data-aos="fade-up" data-aos-delay="100">
                    <a href="{% url 'contact:contact_us' %}" class="btn btn-outline-white-reverse">Contate-nos</a>
                </div>
            </div>
        </div>
    </div>
    <section class="section sec-news">
    <div class="container">
        <div class="row mb-5 mt-3">
            <div class="col-lg-7">
                <h2 class="heading text-primary">Postagens Recentes</h2>
            </div>
        </div>

        <div class="row">
            {% for post in posts %}
            <div class="col-lg-4">
                <div class="card post-entry mb-5">
                    <a href="{{ post.get_absolute_url }}"><img src="{{ post.img.url }}" class="card-img-top" alt="Image"></a>
                    <div class="card-body">
                        <div><span class="text-uppercase font-weight-bold date">{{ post.publish }}</span> </div>
                        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title|safe|truncatewords:3}}</a></h5>
                        <p>{{ post.body|safe|truncatewords:20|linebreaks }}</p>
                        <p class="mt-05 mb-0"><a href="{{ post.get_absolute_url }}">leia mais</a></p>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
    </section>
{#    <div class="album py-5 bg-light">#}
{#        <div class="container">#}
{##}
{#            <h1 class="fw-light text-center text-lg-start mt-4 mb-0">Postagens Recentes</h1>#}
{##}
{#            <hr class="mt-2 mb-5">#}
{##}
{#                <section class="bg-light py-4 my-5">#}
{#                    <div class="container">#}
{#                        <div class="row">#}
{#                            {% for post in posts %}#}
{#                            <div class="mb-4">#}
{#                                    <div class="body">#}
{#                                        <h3 class="title"><a href="{{ post.get_absolute_url }}" class="text-secondary">{{ post.title|title }}</a></h3>#}
{#                                        <br>#}
{#                                          <img src="{{ post.img.url }}" style="width: 300px; height: 500px;"#}
{#                                         class="card-image-top " alt="{{ post.title }}">#}
{#                                        <br>#}
{##}
{#                                        <p class="text">{{ post.body|safe|truncatewords:50|linebreaks}} </p>#}
{#                                        <small class="text-muted">Publicado: {{ post.publish|timesince }} atrás, por {{ post.author.first_name|title }}.</small>#}
{#                                        <br>#}
{#                                        <br>#}
{#                                    </div>#}
{#                            </div>#}
{#                            {% endfor %}#}
{##}
{##}
{#                        </div>#}
{##}
{#                    </div>#}
{#                <br>#}
{#                <a href="{% url 'blog:post_list' %}" class="btn btn-primary">Ver todas</a>#}
{#                </section>#}
{#        </div>#}
{#    </div>#}
{% endblock %}