assembleiaproject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<slug:post>/', views.post_detail, name='post_detail')
]

assembleiaproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assembleiaproject.base.urls')),
    path('blog/', include('assembleiaproject.blog.urls')),
    path('galeria/', include('assembleiaproject.gallery.urls')),
    path('account/', include('assembleiaproject.account.urls')),
    path('contato/', include('assembleiaproject.contact.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'assembleiaproject.base.views.handler500'
handler404 = 'assembleiaproject.base.views.handler404'

assembleiaproject/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.conf import settings
from django.utils import timezone
from taggit.managers import TaggableManager
from tinymce.models import HTMLField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(_('title'), max_length=250)
    slug = models.SlugField(_('slug'), max_length=250)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, related_name='blog_posts')
    body = HTMLField(_('body'))
    publish = models.DateTimeField(_('publish'), default=timezone.now)
    img = models.ImageField(upload_to='blog_img')
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('updated'), auto_now=True)
    status = models.CharField(_('status'), max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish', )
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,

                             self.slug])

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

assembleiaproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from taggit.models import Tag


# Create your views here.
def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'page': page,
               'posts': posts,
               'tag': tag,
               'section': 'blog'
               }

    return render(request, 'post/list.html', context)


def post_detail(request, year, month, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month)

    context = {'post': post}
    return render(request, 'post/detail.html', context)

assembleiaproject/blog/templates/post/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="section">
        <div class="hero overlay inner-page">
            <img src="images/blob.svg" alt="" class="img-fluid blob">
            <div class="container">
                <div class="row align-items-center justify-content-center text-center pt-5">
                    <div class="col-lg-6">
                        <p data-aos="fade-up" class="meta">por <a href="#">{{ post.author }}</a> &bullet; em <a href="#">{{ post.publish }}</a></p>
                        <h1 class="heading mb-3" data-aos="fade-up" data-aos-delay="100">{{ post.title|title }}</h1>
                        <img src="{{ post.img.url }}" alt="Image" class="img-fluid rounded ">

                    </div>

                </div>
            </div>
        </div>


        <div class="row justify-content-center align-items-stretch">
            <article class="col-lg-8 order-lg-2 px-lg-5">
{#                <header>#}
{#                    <br>#}
{#                    <h2 class="header mb-3" data-aos="fade-up">#}
{#                        {{ post.title|title }}#}
{#                    </h2>#}
{#                    <p class="text-muted">Publicado em#}
{#                        <time datetime="2021-04-12T13:00:24+01:00">{{ post.created }}</time>#}
{#                        por <a href="#">{{ post.author.first_name }}</a></p>#}
{#                </header>#}

{#                <img src="{{ post.img.url }}" alt="Image" class="img-fluid rounded justify-content-center">#}

                <p>{{ post.body|safe }}</p>
                <br>

                <div class="pt-5 categories_tags">
                    <p>Tags: {{ post.tags }}</p>
                </div>

                <div class="post-single-navigation d-flex align-items-stretch">
                    <a href="#" class="mr-auto w-50 pr-4">
                        <span class="d-block">Previous Post</span>
                        A Mounteering Guide For Beginners
                    </a>
                    <a href="#" class="ml-auto w-50 text-right pl-4">
                        <span class="d-block">Next Post</span>
                        12 Creative Designers Share Ideas About Web Design
                    </a>
                </div>
            </article>
        </div>
    </div>
{% endblock content %}

assembleiaproject/blog/templates/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

assembleiaproject/blog/templates/post/list.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
<div class="container">
    <div class="row g-5">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 mt-5 fst-italic border-bottom">
                IAD Missionária
            </h3>

            {% if tag %}
            <h2> Postagens com tag "{{ tag.name }}"</h2>
            {% endif %}

            {% for post in posts %}
            <article class="blog-post">
                <a href="{{ post.get_absolute_url }}" class="blog-post-title">{{ post.title|title }}</a>
                <p class="blog-post-meta">{{ post.publish }} <a href="#">{{ post.author.first_name }}</a></p>

                <p> {{ post.body|safe|truncatewords:90|linebreaks}}</p>
                <hr>

            </article>

                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>

            {% endfor %}

           {% include 'post/pagination.html' with page=posts %}

        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-light rounded">
                    <h4 class="fst-italic">Publicações</h4>
                    <p class="mb-0">Temos {% total_posts %} postagens disponiveis.</p>
                     <h3>Ultimas Publicações</h3>
                {% shoow_latest_posts 3 %}
                </div>


{#                <div class="p-4">#}
{#                    <h4 class="fst-italic">Archives</h4>#}
{#                    <ol class="list-unstyled mb-0">#}
{#                        <li><a href="#">March 2021</a></li>#}
{##}
{#                    </ol>#}
{#                </div>#}

{#                <div class="p-4">#}
{#                    <h4 class="fst-italic">Elsewhere</h4>#}
{#                    <ol class="list-unstyled">#}
{#                        <li><a href="#">GitHub</a></li>#}
{#                        <li><a href="#">Twitter</a></li>#}
{#                        <li><a href="#">Facebook</a></li>#}
{#                    </ol>#}
{#                </div>#}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

assembleiaproject/blog/templates/post/pagination.html
 <nav aria-label="...">
                <ul class="pagination">
                    {% if page.has_previous %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="#">{{ page.number }}</a></li>
<!--                    <li class="page-item active" aria-current="page">-->
<!--                        <a class="page-link" href="#">2</a>-->
<!--                    </li>-->
                    {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>